@startuml "cinnamon cinemas"
skinparam ClassAttributeIconSize 0

class Theatre {
    - seats : List<Seat>

    + Theatre(rowLetters : List<string>, columnNumbers : List<int>)

    + GetSeats() : List<Seat>

    + GetAvailableSeatCounts() : int
    + AllocateSeat(number : int) : boolean
}

class Seat <<struct>> {
    - status : Status
    - seatNumber : string

    + Seat(seatNumber : string)

    + GetStatus() : Status
    + GetSeatNumber() : string

    + allocate() : void
}

Enum Status {
    available
    allocated
}

Theatre o-- Seat
Seat o-- Status

@enduml