@startuml "cinnamon cinemas"
skinparam ClassAttributeIconSize 0

class TheatrePrinter {
    + Print(theatre : Theatre) : void
    + Print(theatre : Theatre, recentlyAllocatedSeats : List<Seat>) : void
}

interface ISeatNumberGenerator {
    + GenerateSeatNumber(rowNumber : int, columnNumber : int) : string
}

class SeatNumberGenerator {
    + GenerateSeatNumber(rowNumber : int, columnNumber : int) : string
}

class Theatre {
    - rowCount : int
    - columnCount : int
    - seats : List<Seat>

    + Theatre(\n\
        rowCount : int, \n\
        columnCount : int, \n\
        seatNumberGenerator : ISeatNumberGenerator)

    + GetRowCount() : int
    + GetColumnCount() : int
    + GetSeats() : List<Seat>

    + GetAvailableSeatsCount() : int
    + AllocateSeats(number : int) : List<Seat>
}

class Seat {
    - status : SeatStatus
    - seatNumber : string

    + Seat(seatNumber : string)

    + GetStatus() : SeatStatus
    + GetSeatNumber() : string
    + Allocate() : void
}

Enum SeatStatus {
    Available
    Allocated
}

TheatrePrinter --> Theatre
TheatrePrinter ---> Seat

Theatre o-- Seat
Theatre --> ISeatNumberGenerator

ISeatNumberGenerator <|.. SeatNumberGenerator

Seat o-- SeatStatus

@enduml